config/routes.rb
Rails.application.routes.draw do
     # Authorization
   devise_for :users
  
   devise_scope :user do  
      get '/users/sign_out' => 'devise/sessions#destroy'     
   end
 #/////////////////////////////////////////////////////////////////////////// 
  root to: "home#index"
  get '/' =>'home#index' 
  

  resources :senses do
       resources :comments 
     end 
  
  resources :things do
       resources :comments 
     end 
  
  resources :articles do
       resources :comments 
     end  
     
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    
    has_one_attached :image # Foto!
    has_rich_text :text #Trix
    #validates :title, presence: true, length: {minimum: 2} #walidacija
    validates :text, presence: true, length: {minimum: 2}

    has_many :comments, as: :commentable, dependent: :destroy# Podkluchenie "Comments" delaem
       
    belongs_to :choice
    belongs_to :local
    
    def self.ransackable_attributes(auth_object = nil)
        ["image", "created_at", "id", "local_id", "choice_id", "text", "title", "updated_at"]
        end
      def self.ransackable_associations(auth_object = nil)
        ["comments", "local", "choice"]
        end
      
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]# Connection "user" 
    before_action :set_article!, only: %i[show destroy edit update]  # @article = Article.find params[:id]   "Refactoring"
                                                               
    
    def index   # 4: Wywod wsech zapisej!
       @articles = Article.all
       @choice = Choice.all
       @locals = Local.all
       @q = Article.ransack(params[:q])
       @pagy,@articles = pagy @q.result(distinct: true),items:3
    end
    
   def show  # 3: Wywodim bazu po :ID
       @commentable = @article
       @comment = Comment.new
       #@article = Article.find params[:id]  :before_action :set_article! "Refactoring"
       @locals = Local.new
   end
      
  
   def new  # 1: создать - new (отобразить форму. GET)
       #@article = Article.new  # Пустым оставлять тельзя!
       @choice = Choice.all
       @locals = Local.all
       @q = Article.ransack(params[:q])
       @articles = @q.result(distinct: true)
      end
    
   def create # 2: create (отправить форму. POST)   
       @article = Article.new(article_params)
       @article = current_user.articles.build(article_params)# Connection "user"    
    if @article.valid?
       @article.save 
       flash[:success] = "Оголошення Утворено!"   #Window Podtwerzdenija
       redirect_to @article 
    elsif
       @locals = Local.all
       @choice = Choice.all
       else  
      render action: 'new'  #"perenaprowlenie"
     end
   end
    
   def edit   # 5: Wozwrat i Redactirowanie
      #@article = Article.find params[:id]    :before_action :set_question! "Refactoring"
   end
  
   def update #6  Wnosim izmenrnie w redaktirowanie
      #@article = Article.find(params[:id])      :before_action :set_article! "Refactoring"
    if @article.update(article_params) # Obnowlaem s nowymi parametromi
       redirect_to @article
       flash[:success] = "Оголошення Редоговане!" #Window Podtwerzdenija
      else
       render action: 'edit'    #"perenaprowlenie"
    end
  end
  
  def destroy # Delite publikacij
    #@article = Article.find(params[:id]) #:before_action :set_article! "Refactoring"
    @article.destroy
    flash[:success] = "Оголошення Видалине!"     #Window Podtwerzdenija
    redirect_to @article  #"perenaprowlenie"
  end
  
  #////////////////////////////////////////////////////////////////////////////////////
   private
  
    def article_params
      params.require(:article).permit(:title, :text, :local_id, :choice_id, :image)
   end
  
    def set_article!  # :before_action :set_article! only[show destroy edit update] "Refactoring"
      @article = Article.find(params[:id])
   end
  


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<br>
<h2><%#= t'.title'%></h2>  
                  <!#5 Wozwrat i Redactirowanie>       
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
 <%= select(:article,:choice_id, Choice.all.collect {|choice| [choice.title, choice.id]})%>
<%#= render 'shared/errors', object: @article %> <!Walidacija - papka shared/_errors>
<%# if @article && @article.errors.full_messages.any?%> <!Prowerka! Esli estj ochybka to nepropustit>
<%# end%>
 <%= select(:article,:local_id, Local.all.collect {|local| [local.title, local.id]})%>

<br>
<br>
<label class="label">Заголовок</label>
<div class="col-sm-10">          <!Walidacija CSS --required: true, minlength:2,>
    <%= f.text_field :title, placeholder: "Title", class: "form-control"%>
</div>

<br>
<label class="label">Текст</label>
 <div class="col-sm-10">    <!Walidacija CSS  --required: true, minlength:2,>
    <%= f.rich_text_area :text, placeholder: "Text", class: "form-control"%>
 </div>

<br>
<div class="col-sm-10">     
    <%= f.file_field :image, class: "btn btn-outline-primary btn-sm"%>
</div>
  <br>
  
  <%= f.submit ('Редагувати'), class: "btn btn-primary"%>


<% end %>

<! Все находитсья  в  " edit.html.erb">
<br>
<%= link_to "Показати всi оголошення!",articles_path, class:"button is-danger is-inverted" %>

app/views/articles/index.html.erb
<% provide :page_title, 'Люди' %> <!Podpis w ikonke>
<!% currently_art "Articles" %>
<br>
<form class="d-flex" role="search">
     <%= search_form_for @q do |f| %>
       <%= f.search_field :title_or_text_cont, class:"form-control me-2", type:"search", placeholder:"Введіть ключове слово пошуку!"%> 
      <%= f.submit "Шукати!", class:"btn btn-outline-success"%>
    <% end %>
  </form>
 <br>

<p>
<%= link_to "Нове Оголошення", new_article_path, class: "button big gray bi bi-pencil-square" %>
</p>
 
 <div class="container-fluid">
 <form class="d-flex" role="search">
 <%= search_form_for @q do |f| %>                                        
       <%= f.select :choice_id_eq, @choice.map { |t| [t.title, t.id] }, :include_blank => "Всi",required: false %>                                                                
                                                                       <!All posts in dropdown>
      .<%= f.select :local_id_eq, @locals.map { |t| [t.title, t.id] },:include_blank => "Вся Україна", required: false %>
      <%= f.submit "Шукати!", class:"button is-primary "%>
    <% end %>
    </form>
  <%= sort_link(@q, :title, "Oстаннє", default_order: :desc)%> <!":asc">
   </div>
<br>
<br>
<% @articles.each do |article| %>
     <h4><%= article.user.username%></h4>
  <h4>
  <%= link_to article.title, article_path(article) %>
  </h4>

  <p class="my-2">
  <% if article.image.attached?%> <! if image nil>
  <%= link_to image_tag(article.image, style: "width: 380px; height: auto", class: 'img-thumbnail thumb'), article_path(article)%>
  <% end %>
  </p>           
  
  <h4 class="my-2">
  <%= article.text %>
  </h4>
        <section class="card-text">
           <! Podkluchenie time pod soobzheniem!>
  <time datetime="<%= article.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= article.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
           </section>            
   <!hr>
                     <!Ssylka na statью>
  <p><!%= link_to "New article", new_article_path(article),class: "btn btn-primary" %> 
     <%#= link_to  "Show article", article_path(article),class: "btn btn-primary btn-sm"%>  
     <%= link_to  "Редагувати", edit_article_path(article),class: "btn btn-secondary btn-sm"%> 
     <%= link_to 'Видалити', article_path(article), data: {'turbo-method': :delete,'turbo-confirm': 
     'Are you sure?'}, class:"btn btn-danger btn-sm"%>
   <hr>              
                       <! rails routes>                         <!Eto JS window "Udalit post">
        
     <!/div>
<% end %>
   
   <br>
   <%== pagy_bootstrap_nav(@pagy)%>   <!Pagy "gem pagy" razbiw na stranicy Podkluchenie> 
   <br>

app/views/articles/new.html.erb
<% provide :page_title, 'Нове оголошення' %> <!Podpis w ikonke>
<br>
<h2>Нове Оголошення</h2>

<%= form_for :article, url: articles_path, data: {turbo:false}  do |f| %>
   
   <%= select(:article,:choice_id, Choice.all.collect {|choice| [choice.title, choice.id]})%>
   <%#= select(:article,:local_id, options_from_collection_for_select(@locals, "id","title", @article.present? ? @article.local_id : nil), {})%>
    <%= select(:article,:local_id, Local.all.collect {|local| [local.title, local.id]})%>
<%#= render 'shared/errors', object: @article %> <!Walidacija - papka shared/_errors>
<%# if @article && @article.errors.full_messages.any?%> <!Prowerka! Esli estj ochybka to nepropustit>
<%# end%>
<br>
<br>

 <label class="label">Заголовок</label>
<div class="col-sm-10">          <! Walidacija CSS ---required: true, minlength:2,>
    <%= f.text_field :title, placeholder: "Заголовок", required: true, minlength:2, class: "form-control"%>
</div>

<br>
 <label class="label">Текст</label>
<div class="col-sm-10">     <! Walidacija CSS ---required: true, minlength:2,>
    <%= f.rich_text_area :text, placeholder: "Teкст", class: "form-control" %>
</div>

<br>
<div class="col-sm-10">     
    <%= f.file_field :image, class: "btn btn-outline-primary btn-sm"%>
</div>
<br>
  
  <%= f.submit "Нове оголошення", class: "btn btn-primary"%>

<%end%>

<br>
<br>
<%= link_to "Показати всi оголошення!",articles_path, class:"button is-danger is-inverted" %>

app/views/articles/show.html.erb
<%# provide :page_title, 'Article has been created!!!' %> <!Podpis w ikonke "Kakaja stranica">


 <H5>Область: <%= @article.local.title%></H5>
  <h4><%= @article.user.username%></h4>  <!Connect "usera!!">
 <p class="mb-2"><%= @article.title %></p>
 
 <% if @article.image.attached?%> <! if image nil>
 <%= image_tag @article.image, style: "width: 380px; height: auto", class: 'img-thumbnail thumb'%>
  <% end %>
 <br>
 <p class="lead my-3"><%= @article.text %></p>

             <! Podkluchenie time pod soobzheniem!>
  <time datetime="<%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
   <br>
   <%= link_to ('Редагувати'), edit_article_path(@article),class: "btn btn-secondary btn-sm"%> 
   <%= link_to ('Видалити'), article_path(@article), data: {'turbo-method': :delete,'turbo-confirm': 
     'Are you sure?'}, class:"btn btn-danger btn-sm"%>
   <%= link_to "Показати всi оголошення!",articles_path, class:"button is-danger is-inverted" %> <!Prawelnaja ssylka>
<!/////////////////////////////////////////////////////////////////////////////////////////>

 <hr class="my-3">
<!h4> <!/h4>

<a class="button big gray bi bi-pencil-square" href="#collapseExample" role="button" data-bs-toggle="collapse" aria-expanded="false">
     <%= ('Коментувати!')%>
  </a>
<br>
                     <!Dropdown Topic>
  <ul class="collapse" id="collapseExample"  data: {'bs-toggle': 'collapse'}>
                      <!Dobawil Comment>
 
 <%= form_with model: [@commentable, @comment] do |f| %>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :Коментар %>
    </div>

    <div class="col-sm-10">                     <! Walidacija CSS ---required: true, minlength:2,>
      <%= f.rich_text_area :body, class: 'form-control', required: true, minlength:2%>
    </div>
  </div>

  <%= f.submit "Создати", class: 'button is-primary' %>
 <% end %>
 </ul>
<!/////////////////////////////////////////////////////////////////////////////////////>

<!h4 class="mt-5"><!/h4>
<br>
<% @commentable.comments.each do |comment| %>
  
  <h5><%= comment.user.username%></h5> 
  <article class="mb-3 card" id="comment-<%= comment.id %>">
      <div class="card-body">
           <! Podkluchenie time pod soobzheniem!>
  <time datetime="<%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
         
         <section class="card-text">
                  <p>
                    <%= comment.body %>
                  </p>
         </section>
              
 
 <%= link_to  "Редагувати", edit_article_comment_path(@article,comment),class: "btn btn-secondary btn-sm"%> 
 <%= link_to 'Видалити', article_comment_path(@article, comment), class: 'btn btn-danger btn-sm',
      data: {method: :delete, confirm: "Are you sure?"} %>
   </div>
 </article>
<%end%>