config/routes.rb
Rails.application.routes.draw do
     # Authorization
   devise_for :users
  
   devise_scope :user do  
      get '/users/sign_out' => 'devise/sessions#destroy'     
   end
 #/////////////////////////////////////////////////////////////////////////// 
  root to: "home#index"
  get '/' =>'home#index' 
  

  resources :senses do
       resources :comments 
     end 
  
  resources :things do
       resources :comments 
     end 
  
  resources :articles do
       resources :comments 
     end  
     
end

app/models/thing.rb
class Thing < ApplicationRecord
    belongs_to :user
    
    has_one_attached :image # Foto!
    has_rich_text :text #Trix
    
    has_many :comments, as: :commentable, dependent: :destroy # Podkluchenie "Comments" Rukami 
    
    belongs_to :choice
    belongs_to :local
    
    def self.ransackable_attributes(auth_object = nil)
        ["image", "created_at", "id", "local_id", "choice_id", "text", "title", "updated_at"]
        end
      def self.ransackable_associations(auth_object = nil)
        ["comments", "local", "choice"]
        end
      
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
    before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
    before_action :set_thing!, only: %i[show destroy edit update]  # @article = Article.find params[:id]   "Refactoring"
                                                               
    def index  
        @things = Thing.all
        @locals = Local.all
        @choice = Choice.all
        @q = Thing.ransack(params[:q])
        @pagy,@things = pagy @q.result(distinct: true),items:3
      end
     
    def show  
        @commentable = @thing
        @comment = Comment.new
        @locals = Local.new
        # @thing = Thing.find(params[:id]) :before_action :set_thing! only[show destroy edit update] "Refactoring"
     end
       
   
    def new  
        @thing = Thing.new  
        @locals = Local.all
        @choice = Choice.all
      end
     
    def create # 2: create (отправить форму. POST)   
        @thing = Thing.new(thing_params)
        @thing = current_user.things.build(thing_params)# Connection "user" 
     if @thing.valid?
        @thing.save 
        flash[:success] = "Оголошення Утворино"   
        redirect_to @thing 
     else
        render action: 'new' 
      end
    end
     
    def edit   
       #@thing = Thing.find params[:id] :before_action :set_thing! "Refactoring"
     end
   
    def update 
       #@thing = Thing.find(params[:id]) before_action :set_shing! "Refactoring"
     if @thing.update(thing_params) # Obnowlaem s nowymi parametromi
        redirect_to @thing
        flash[:success] = "Оголошення Редаговане" #Window Podtwerzdenija
       else
        render action: 'edit'    #"perenaprowlenie"
     end
   end
   
   def destroy 
     #@thing = Thing.find(params[:id]) # :before_action :set_thing! "Refactoring"
     @thing.destroy
     flash[:success] = "Оголошення Видалине"     #Window Podtwerzdenija
     redirect_to @thing  
   end
   
   #////////////////////////////////////////////////////////////////////////////////////
    private
   
     def thing_params
       params.require(:thing).permit(:title, :text, :local_id, :choice_id, :image)
    end
   
     def set_thing!  # :before_action :set_thing! only[show destroy edit update] "Refactoring"
       @thing = Thing.find(params[:id])
    end
   
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/edit.html.erb
<br>
<h2><%#= t'.title'%></h2>  
                  <!#5 Wozwrat i Redactirowanie>       
<%= form_for :thing, url: thing_path(@thing), method: :patch do |f| %>
 
 <%= select(:thing,:choice_id, Choice.all.collect {|choice| [choice.title, choice.id]})%>
<%#= render 'shared/errors', object: @article %> <!Walidacija - papka shared/_errors>
<%# if @article && @article.errors.full_messages.any?%> <!Prowerka! Esli estj ochybka to nepropustit>
<%# end%>
 <%= select(:thing,:local_id, Local.all.collect {|local| [local.title, local.id]})%>

<br>
<br>
<label class="label">Заголовок</label>
<div class="col-sm-10">          <!Walidacija CSS --required: true, minlength:2,>
    <%= f.text_field :title, placeholder: "Title", class: "form-control"%>
</div>

<br>
<label class="label">Текст</label>
 <div class="col-sm-10">    <!Walidacija CSS  --required: true, minlength:2,>
    <%= f.rich_text_area :text, placeholder: "Text", class: "form-control"%>
 </div>

<br>
<div class="col-sm-10">     
    <%= f.file_field :image, class: "btn btn-outline-primary btn-sm"%>
</div>
  <br>
  
  <%= f.submit ('Редагувати'), class: "btn btn-primary"%>


<% end %>

<! Все находитсья  в  " edit.html.erb">
<br>
<%= link_to "Показати всi оголошення!",things_path, class:"button is-danger is-inverted" %>

app/views/things/index.html.erb
<% provide :page_title, 'Речi' %> <!Podpis w ikonke>

<br>
<form class="d-flex" role="search">
     <%= search_form_for @q do |f| %>
       <%= f.search_field :title_or_text_cont, class:"form-control me-2", type:"search", placeholder:"Введіть ключове слово пошуку!"%> 
      <%= f.submit "Шукати!", class:"btn btn-outline-success"%>
    <% end %>
  </form>
  <br>

<p>
<%= link_to "Нове Оголошення", new_thing_path, class: "button big gray bi bi-pencil-square" %>
</p>
 
 <div class="container-fluid">
 <form class="d-flex" role="search">
 <%= search_form_for @q do |f| %>                                           
          <%= f.select :choice_id_eq, @choice.map { |t| [t.title, t.id] }, :include_blank => "Всi", required: false %>                                                                                                                                
                                                                             <!all post in dropdown>
        .<%= f.select :local_id_eq, @locals.map { |t| [t.title, t.id] }, :include_blank => "Вся Україна", required: false %>
<!br><%= f.submit "Шукати!", class:"button is-primary "%>
    <%#= f.submit "Шукати!", class:" btn btn-outline-success"%>
    <% end %>
    </form>
   <%= sort_link(@q, :title, "Oстаннє", default_order: :desc)%> <!":asc">
  </div>

<br>
<% @things.each do |thing| %>
  <h4>
  <%= link_to thing.title, thing_path(thing) %>
  </h4>

  <p class="my-2">
  <% if thing.image.attached?%> <! if image nil>
  <%= link_to image_tag(thing.image, style: "width: 380px; height: auto", class: 'img-thumbnail thumb'), thing_path(thing)%>
  <% end %>
  </p>           
  
  <h4 class="my-2">
  <%= thing.text %>
  </h4>
        <section class="card-text">
           <! Podkluchenie time pod soobzheniem!>
  <time datetime="<%= thing.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= thing.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
           </section>            
   <!hr>
                     <!Ssylka na statью>
  <p><!%= link_to "New article", new_article_path(article),class: "btn btn-primary" %> 
     <%#= link_to  "Show article", article_path(article),class: "btn btn-primary btn-sm"%>  
     <%= link_to  "Редагувати", edit_thing_path(thing),class: "btn btn-secondary btn-sm"%> 
     <%= link_to 'Видалити', thing_path(thing), data: {'turbo-method': :delete,'turbo-confirm': 
     'Are you sure?'}, class:"btn btn-danger btn-sm"%>
   <hr>              
                    
<% end %>
   <br>
   <%== pagy_bootstrap_nav(@pagy)%>   <!Pagy "gem pagy" razbiw na stranicy Podkluchenie> 
   <br>

 

app/views/things/new.html.erb
<% provide :page_title, 'Нове Оголошення' %> <!Podpis w ikonke>
<br>
<h2>Нове Оголошення</h2>

<%= form_for :thing, url: things_path, data: {turbo:false}  do |f| %>
    <%= select(:thing,:choice_id, Choice.all.collect {|choice| [choice.title, choice.id]})%>
   <!div class="container-fluid">
   <%#= select(:thing,:local_id, options_from_collection_for_select(@locals, "id","title", @article.present? ? @article.local_id : nil), {})%>
    <%= select(:thing,:local_id, Local.all.collect {|local| [local.title, local.id]})%>
   <!/div>
<%#= render 'shared/errors', object: @article %> <!Walidacija - papka shared/_errors>
<%# if @article && @article.errors.full_messages.any?%> <!Prowerka! Esli estj ochybka to nepropustit>
<%# end%>
<br>
<br>

 <label class="label">Заголовок</label>
<div class="col-sm-10">          <! Walidacija CSS ---required: true, minlength:2,>
    <%= f.text_field :title, placeholder: "Заголовок", required: true, minlength:2, class: "form-control"%>
</div>

<br>
 <label class="label">Текст</label>
<div class="col-sm-10">     <! Walidacija CSS ---required: true, minlength:2,>
    <%= f.rich_text_area :text, placeholder: "Текст", required: true, minlength:2, class: "form-control"%>
</div>

<br>
<div class="col-sm-10">     
    <%= f.file_field :image, class: "btn btn-outline-primary btn-sm"%>
</div>
<br>
  
  <%= f.submit "Нове оголошення", class: "btn btn-primary"%>

<%end%>

<br>
<br>
<%= link_to "Показати всi оголошення!",things_path, class:"button is-danger is-inverted" %>

app/views/things/show.html.erb
<%# provide :page_title, 'Article has been created!!!' %> <!Podpis w ikonke "Kakaja stranica">


 <H5>Область: <%= @thing.local.title%></H5>
 <h4><%= @thing.user.username%></h4>
 <p class="mb-2"><%= @thing.title %></p>
 
 <% if @thing.image.attached?%> <! if image nil>
 <%= image_tag @thing.image, style: "width: 380px; height: auto", class: 'img-thumbnail thumb'%>
  <% end %>
 <br>
 <p class="lead my-3"><%= @thing.text %></p>

             <! Podkluchenie time pod soobzheniem!>
  <time datetime="<%= @thing.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= @thing.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
   <br>
   <%= link_to ('Редагувати'), edit_thing_path(@thing),class: "btn btn-secondary btn-sm"%> 
   <%= link_to ('Видалити'), thing_path(@thing), data: {'turbo-method': :delete,'turbo-confirm': 
     'Are you sure?'}, class:"btn btn-danger btn-sm"%>
   <%= link_to "Показати всi оголошення!",things_path, class:"button is-danger is-inverted" %> <!Prawelnaja ssylka>
<!/////////////////////////////////////////////////////////////////////////////////////////>

 <hr class="my-3">
<!h4> <!/h4>

<a class="button big gray bi bi-pencil-square" href="#collapseExample" role="button" data-bs-toggle="collapse" aria-expanded="false">
     <%= ('Коментувати!')%>
  </a>
<br>
                     <!Dropdown Topic>
  <ul class="collapse" id="collapseExample"  data: {'bs-toggle': 'collapse'}>
                      <!Dobawil Comment>
 
 <%= form_with model: [@commentable, @comment] do |f| %>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :Коментар %>
    </div>

    <div class="col-sm-10">                     <! Walidacija CSS ---required: true, minlength:2,>
      <%= f.rich_text_area :body, class: 'form-control', required: true, minlength:2%>
    </div>
  </div>

  <%= f.submit "Создати", class: 'button is-primary' %>
 <% end %>
 </ul>
<!/////////////////////////////////////////////////////////////////////////////////////>

<!h4 class="mt-5"><!/h4>
<br>
<% @commentable.comments.each do |comment| %>
  <h5><%= comment.user.username%></h5> 
  <article class="mb-3 card" id="comment-<%= comment.id %>">
      <div class="card-body">
           <! Podkluchenie time pod soobzheniem!>
  <time datetime="<%= @thing.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= @thing.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
         
         <section class="card-text">
                  <p>
                    <%= comment.body %>
                  </p>
         </section>
              
 
 <%= link_to  "Редагувати", edit_thing_comment_path(@thing,comment),class: "btn btn-secondary btn-sm"%> 
 <%= link_to 'Видалити', thing_comment_path(@thing, comment), class: 'btn btn-danger btn-sm',
      data: {method: :delete, confirm: "Are you sure?"} %>
   </div>
 </article>
<%end%>