config/routes.rb
Rails.application.routes.draw do
     # Authorization
   devise_for :users
  
   devise_scope :user do  
      get '/users/sign_out' => 'devise/sessions#destroy'     
   end
 #/////////////////////////////////////////////////////////////////////////// 
  root to: "home#index"
  get '/' =>'home#index' 
  

  resources :senses do
       resources :comments 
     end 
  
  resources :things do
       resources :comments 
     end 
  
  resources :articles do
       resources :comments 
     end  
     
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% provide :page_title, 'Головна' %> <!Podpis w ikonke "Kakaja stranica">
<br>
<br>
 <!form class="d-flex" role="search">
      <!input class="form-control me-2" type="search" placeholder="Пошук" aria-label="Пошук">
      <!button class="btn btn-outline-success" type="submit"><!/button>
  <!/form>
<!br>
<br>
 <div class="container-md">
  <div class="row g-3">
    <div class="col-12 col-md-6 col-lg-4">
       <div class="card">
          <%= link_to image_tag("piople.jpg",:size => "330x320",class: "card-img-top"),articles_path %>
            <div class="card-body">
            <H5 class="card-title text-center">Люди</H5>
           <p class="card-texa">В цьому розділі ви можете шукати та знайти людей.</p>
         </div>
        </div>
       </div>
     <div class="col-12 col-md-6 col-lg-4">
      <div class="card">
        <%= link_to image_tag("dag.jpg",:size => "330x320",class: "card-img-top"),senses_path %>
        <div class="card-body">
          <H5 class="card-title text-center">Тварини</H5>
          <p class="card-texa">В цьому розділі ви можете шукати та знайти людей.</p>
        </div>
       </div>
      </div>
  
     <div class="col-12 col-md-6 col-lg-4">
      <div class="card">
      <%= link_to image_tag("thing.jpg",:size => "330x320",class: "card-img-top"),things_path %>
         <div class="card-body">
          <H5 class="card-title text-center">Речi</H5>
         <p class="card-texa">В цьому розділі ви можете шукати та знайти людей.</p>
        </div>
       </div>
      </div>
   </div>
  </div>
 <!/div>

 
 